<?php

namespace App\Presenters;

use Nette,
		App\Model;


/**
 * Homepage presenter.
 */
class HomepagePresenter extends BasePresenter
{

	/** @var  Nette\Database\Context */
	private $database;

	public function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub
		$this->flashMessage("startup se spustil...", "info");
	}

	public function __construct(Nette\Database\Context $database)
	{
		$this->database = $database;
	}

	public function renderDefault()
	{
		$this->template->posts = $this->database->table("posts")->order("created_at DESC")->limit(5);

	}

}